[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"

# Environment Variables for Brevo Email Integration
# Set these in your Netlify dashboard:
# - BREVO_API_KEY: Your Brevo API key (format: xkeysib-xxxxxxxxxx)
# - CONTACT_TO_EMAIL: Email address to receive contact form submissions