/* Auto-generated from 7a87061fe2ccee0897c14e923c3def6917f5306a4ef04e17d9b5346f7d32b435-private.pem.key */
/* DO NOT EDIT - Generated by scripts/convert_certs.py */

#ifndef DEVICE_PRIVATE_KEY_PEM_H
#define DEVICE_PRIVATE_KEY_PEM_H

static const char device_private_key_pem[] =
"-----BEGIN RSA PRIVATE KEY-----\n"
"MIIEowIBAAKCAQEA2AnUVnsNZdTfEg2p3Ynz49l3h/B5O4G5M5FZWhRTYufpw3O4\n"
"CZoboxRX9EhB2K/ooGtyeuISzF56ig73bcuu79E/oyzTLl9NQFPQ1MuYUImQy1QZ\n"
"j1BUyFt8jtwqUkXLIqtgBzKMrVTvkdC8HHVm/mLOVPfAzhItxyGAkm1TkHpKo4qi\n"
"YT5T2L1HzqXtphfv6LZ+RqRi6ZJkJS8yrqM4FDQE24KTeVD9o77XeKTjoR3YvQlj\n"
"ovuqv2bAbylqkZofWQ/KyKBBiMsDx8g8K95ERp/H856diGReo7szoZNWrkqMKLGl\n"
"nxf3hkKadr2f78vXm5sOtkFwvVJjbKXFheibvQIDAQABAoIBAE5piut0sFE0qV6Z\n"
"HP1u89nQdcUecDI8DGd+Kws582YjvMIXP0Yk7EENwjrE+zlV575KIXwekCojZKC1\n"
"e/MbCby7mzhzrZbYOmbNxS9nUjpxI9/Y/4n34z3xjs0fdjD0ah2ETE9wdoT3Hhkz\n"
"xQMjTaWpYTCP2CgzivAK5eq/yaPXRCJT8nKdL3VrHNX6cBsQ9hWbR8W7tsgbNv4E\n"
"3OCv3CTGpKxtTutksX4Y0XypbLV+ae/pVmngM7NtRY6phNV2kv46h+gv0x2x1TgS\n"
"BS5rmUWZRTyYcYl0Jv7LkP7mFkXUgm6vxf3gKtwcjAUwUTo1zyJREpJeZ8Wpf+vt\n"
"gTLDd7UCgYEA+6dcdQsK1J8rX1CZEpT/sceI8yaqUfrn7cnfRfXxDv+RFTOSeTw6\n"
"Rg4Ww1RgI1wbkZnOM7kyyWgsMwzKxzWtUPsfwfFdN7wgDIo+nBUerHaJ56kxcWb7\n"
"F20NBjqwPKwq3ShsKeYqAkzVqavf+Ch24cj4I2FPpCVxa7NUBdK2QqcCgYEA28UA\n"
"djZRF5mghT4ZMDNyZVdDw2Zz/wEiQU6wkfgF/+tP3moLd4zJb2TmiT1jcNh10Oaa\n"
"2UO9N/Vxn15axOetphNRWwCc8TlNRWr71LYQN0Cep4sOigKXebMVzEHoSYCweaPa\n"
"txRfwpMR9KiueDGAGiTQbwjd7kGz/HnnasiS7vsCgYAoKz3B3QJckA+fRkE4yxnJ\n"
"ad09WrWjIla1CR0fkLNqvnaNGM9PlMKEfik6ApTZ8BDie9eDQBOQPJWZjHgtti61\n"
"F3CpR3qms9u1xLdbuK9NvhojJUmkHVkFEz4Z+XI6LQ0mghZJ1dhsx5DvZWT5upPH\n"
"VInvM9A/lk51b4mA6HJ5TwKBgEFJY9q6RhrZs5sBmJ/+GJTMeL/6lqkBoDiAdOnY\n"
"IYgmUoLDRAbO1yR1eBr7Fqh2VYGqkAPNINAX5RowAI0QOkDk6j07kGQE3tSpdIh7\n"
"UZPoaXliUP5kyLUJo4cbaTM0vLhWGepbbhsyb5ob5kCki+a4WwcxPiTCdgKiAEJz\n"
"tVqzAoGBAIfp7Um4JDwp7eoo7P8rWh20bZm/9kqpCiWtyyT999pdmKJD78UtcnKG\n"
"JfFexgbfDSLCANVDcu9Lq/+UxuU3wItQRRj1FO1rtBRqwNnpId8kAr10neESgb4k\n"
"x/bQq/CKIvGfw2p9r/OUvWoJvhBIsSn45J2H4Mt0fSbfDkaco35C\n"
"-----END RSA PRIVATE KEY-----\n"
;

#endif /* DEVICE_PRIVATE_KEY_PEM_H */
