#!/usr/bin/env python3
"""
Convert PEM certificate files to C header files
Usage: python scripts/convert_certs.py
"""
import os
import sys
import glob

def pem_to_c_header(pem_file, output_file, var_name):
	"""Convert a PEM file to a C header with string literal"""

	with open(pem_file, 'r', encoding='utf-8') as f:
		content = f.read()

	if not content.endswith('\n'):
		content += '\n'

	header = f"""/* Auto-generated from {os.path.basename(pem_file)} */
/* DO NOT EDIT - Generated by scripts/convert_certs.py */

#ifndef {var_name.upper()}_H
#define {var_name.upper()}_H

static const char {var_name}[] =
"""

	for line in content.splitlines():
		escaped_line = line.replace('\\', '\\\\').replace('"', '\\"')
		header += f'"{escaped_line}\\n"\n'

	header += ';\n\n#endif /* {0}_H */\n'.format(var_name.upper())

	os.makedirs(os.path.dirname(output_file), exist_ok=True)
	with open(output_file, 'w', encoding='utf-8') as f:
		f.write(header)

	print(f"OK: Generated {output_file}")

def find_cert_file(cert_dir, pattern):
	"""Find certificate file matching pattern"""
	files = glob.glob(f"{cert_dir}/{pattern}")
	return files[0] if files else None

def main():
	cert_dir = 'certs'
	output_dir = 'src/certs'

	print("Converting certificates...")

	if not os.path.exists(cert_dir):
		print(f"ERROR: {cert_dir}/ not found!")
		print(f"   Please create {cert_dir}/ directory and place your AWS certificates there")
		sys.exit(1)

	# Find certificates
	root_ca = find_cert_file(cert_dir, '*AmazonRootCA1*.pem')
	device_cert = find_cert_file(cert_dir, '*certificate*.crt') or find_cert_file(cert_dir, '*certificate*.pem')
	device_key = find_cert_file(cert_dir, '*private*.key') or find_cert_file(cert_dir, '*private*.pem')

	if not all([root_ca, device_cert, device_key]):
		print("ERROR: Missing certificate files!")
		print(f"   Expected files in {cert_dir}/:")
		print(f"   - *AmazonRootCA1*.pem (Root CA)")
		print(f"   - *certificate*.crt or *.pem (Device cert)")
		print(f"   - *private*.key or *.pem (Private key)")
		sys.exit(1)

	print(f"   Found Root CA: {os.path.basename(root_ca)}")
	print(f"   Found Device Cert: {os.path.basename(device_cert)}")
	print(f"   Found Private Key: {os.path.basename(device_key)}")

	# Convert
	pem_to_c_header(root_ca, f'{output_dir}/aws_root_ca.h', 'aws_root_ca_pem')
	pem_to_c_header(device_cert, f'{output_dir}/device_cert.h', 'device_cert_pem')
	pem_to_c_header(device_key, f'{output_dir}/device_key.h', 'device_private_key_pem')

	print("SUCCESS: Certificates converted successfully!")

if __name__ == '__main__':
	main()
